version: "3.4"
services:
  app:
    image: mfekadu/rasa-actions:latest

  db:
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/bitnami/postgresql

volumes:
  db-volume:
    name: db-volume
