version: "3.4"
services:
  rasa-x:
    ports:
      # find production model via http://rasa-x:5002/api/projects/default/models/tags/production
      - "5002:5002"
    # turns out these volumes below are stored in db
    # volumes:
    # - ./config.yml:/app/config.yml
    # - ./domain.yml:/app/domain.yml
    # - ./tests:/app/tests

  rasa-production:
    ports:
      # hack into the rasa-production server
      - "5065:5005"

  rasa-worker:
    ports:
      # hack into the rasa-worker server
      - "5075:5005"

  app:
    image: mfekadu/rasa-actions:latest
    ports:
      # hack into the actions server
      - "5055:5055"

  db:
    ports:
      # hack into the database
      - "5432:5432"
    volumes:
      - db-volume:/bitnami/postgresql

  rabbit:
    ports:
      # hack into the rabbitmq
      - "5672:5672"

  duckling:
    ports:
      # hack into the duckling
      - "8000:8000"

  redis:
    ports:
      # hack into the redis
      - "6379:6379"

  elasticsearch-service:
    # https://docs.docker.com/config/containers/start-containers-automatically/
    restart: always
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
    build: ./elastic
    volumes:
      - ./elastic:/elastic
    environment:
      # - node.name=es01
      - cluster.name=elastic-docker-single-node
      - discovery.type=single-node
      # - discovery.seed_hosts=es02,es03
      # - cluster.initial_master_nodes=es01,es02,es03
      # - bootstrap.memory_lock=true
      # 512 MB of memory ??
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      # map local-port :to: container-port
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html
      - 9200:9200
      - 9300:9300
    # networks:
    #   - elastic

  nimbus-elastic-tf-embed-worker:
    # https://docs.docker.com/config/containers/start-containers-automatically/
    restart: always
    build: ./elastic_tf_embed_worker
    volumes:
      - ./elastic_tf_embed_worker:/app
    expose:
      - "9010"
    environment:
      NIMBUS_ELASTIC_TF_EMBED_WORKER_PORT: "9010"
      ELASTIC_SEARCH_BASE_URL: "http://elasticsearch-service:9200"
      # TODO: come up with good index_name depending on data to be indexed
      ELASTIC_SEARCH_INDEX_NAME: "index_name"
    ports:
      - 9010:9010
    depends_on:
      # TODO: if talk to db, then this services depends on it too
      # cannot index anything without elasticsearch running
      - elasticsearch-service

volumes:
  db-volume:
    name: db-volume
